// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: pkg/proto/follow/follow.proto

package follow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message Definition
type FollowRequestById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequestById) Reset() {
	*x = FollowRequestById{}
	mi := &file_pkg_proto_follow_follow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequestById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequestById) ProtoMessage() {}

func (x *FollowRequestById) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_follow_follow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequestById.ProtoReflect.Descriptor instead.
func (*FollowRequestById) Descriptor() ([]byte, []int) {
	return file_pkg_proto_follow_follow_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRequestById) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolloweeId    uint32                 `protobuf:"varint,1,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	FollowerId    uint32                 `protobuf:"varint,2,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_pkg_proto_follow_follow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_follow_follow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_follow_follow_proto_rawDescGZIP(), []int{1}
}

func (x *FollowRequest) GetFolloweeId() uint32 {
	if x != nil {
		return x.FolloweeId
	}
	return 0
}

func (x *FollowRequest) GetFollowerId() uint32 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

type FollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolloweeId    uint32                 `protobuf:"varint,1,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	FollowerId    uint32                 `protobuf:"varint,2,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_pkg_proto_follow_follow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_follow_follow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_follow_follow_proto_rawDescGZIP(), []int{2}
}

func (x *FollowResponse) GetFolloweeId() uint32 {
	if x != nil {
		return x.FolloweeId
	}
	return 0
}

func (x *FollowResponse) GetFollowerId() uint32 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

type IdListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdList        []uint32               `protobuf:"varint,1,rep,packed,name=id_list,json=idList,proto3" json:"id_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdListResponse) Reset() {
	*x = IdListResponse{}
	mi := &file_pkg_proto_follow_follow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdListResponse) ProtoMessage() {}

func (x *IdListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_follow_follow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdListResponse.ProtoReflect.Descriptor instead.
func (*IdListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_follow_follow_proto_rawDescGZIP(), []int{3}
}

func (x *IdListResponse) GetIdList() []uint32 {
	if x != nil {
		return x.IdList
	}
	return nil
}

type DeleteFollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFollowResponse) Reset() {
	*x = DeleteFollowResponse{}
	mi := &file_pkg_proto_follow_follow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFollowResponse) ProtoMessage() {}

func (x *DeleteFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_follow_follow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFollowResponse.ProtoReflect.Descriptor instead.
func (*DeleteFollowResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_follow_follow_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFollowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_proto_follow_follow_proto protoreflect.FileDescriptor

const file_pkg_proto_follow_follow_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/follow/follow.proto\x12\x06follow\"#\n" +
	"\x11FollowRequestById\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\rFollowRequest\x12\x1f\n" +
	"\vfollowee_id\x18\x01 \x01(\rR\n" +
	"followeeId\x12\x1f\n" +
	"\vfollower_id\x18\x02 \x01(\rR\n" +
	"followerId\"R\n" +
	"\x0eFollowResponse\x12\x1f\n" +
	"\vfollowee_id\x18\x01 \x01(\rR\n" +
	"followeeId\x12\x1f\n" +
	"\vfollower_id\x18\x02 \x01(\rR\n" +
	"followerId\")\n" +
	"\x0eIdListResponse\x12\x17\n" +
	"\aid_list\x18\x01 \x03(\rR\x06idList\"0\n" +
	"\x14DeleteFollowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf5\x02\n" +
	"\rFollowService\x12=\n" +
	"\fCreateFollow\x12\x15.follow.FollowRequest\x1a\x16.follow.FollowResponse\x12>\n" +
	"\tGetFollow\x12\x19.follow.FollowRequestById\x1a\x16.follow.FollowResponse\x12M\n" +
	"\x18GetFollowersByFolloweeID\x12\x19.follow.FollowRequestById\x1a\x16.follow.IdListResponse\x12M\n" +
	"\x18GetFolloweesByFollowerID\x12\x19.follow.FollowRequestById\x1a\x16.follow.IdListResponse\x12G\n" +
	"\fDeleteFollow\x12\x19.follow.FollowRequestById\x1a\x1c.follow.DeleteFollowResponseB\x1bZ\x19services/pkg/proto/followb\x06proto3"

var (
	file_pkg_proto_follow_follow_proto_rawDescOnce sync.Once
	file_pkg_proto_follow_follow_proto_rawDescData []byte
)

func file_pkg_proto_follow_follow_proto_rawDescGZIP() []byte {
	file_pkg_proto_follow_follow_proto_rawDescOnce.Do(func() {
		file_pkg_proto_follow_follow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_follow_follow_proto_rawDesc), len(file_pkg_proto_follow_follow_proto_rawDesc)))
	})
	return file_pkg_proto_follow_follow_proto_rawDescData
}

var file_pkg_proto_follow_follow_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_follow_follow_proto_goTypes = []any{
	(*FollowRequestById)(nil),    // 0: follow.FollowRequestById
	(*FollowRequest)(nil),        // 1: follow.FollowRequest
	(*FollowResponse)(nil),       // 2: follow.FollowResponse
	(*IdListResponse)(nil),       // 3: follow.IdListResponse
	(*DeleteFollowResponse)(nil), // 4: follow.DeleteFollowResponse
}
var file_pkg_proto_follow_follow_proto_depIdxs = []int32{
	1, // 0: follow.FollowService.CreateFollow:input_type -> follow.FollowRequest
	0, // 1: follow.FollowService.GetFollow:input_type -> follow.FollowRequestById
	0, // 2: follow.FollowService.GetFollowersByFolloweeID:input_type -> follow.FollowRequestById
	0, // 3: follow.FollowService.GetFolloweesByFollowerID:input_type -> follow.FollowRequestById
	0, // 4: follow.FollowService.DeleteFollow:input_type -> follow.FollowRequestById
	2, // 5: follow.FollowService.CreateFollow:output_type -> follow.FollowResponse
	2, // 6: follow.FollowService.GetFollow:output_type -> follow.FollowResponse
	3, // 7: follow.FollowService.GetFollowersByFolloweeID:output_type -> follow.IdListResponse
	3, // 8: follow.FollowService.GetFolloweesByFollowerID:output_type -> follow.IdListResponse
	4, // 9: follow.FollowService.DeleteFollow:output_type -> follow.DeleteFollowResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_follow_follow_proto_init() }
func file_pkg_proto_follow_follow_proto_init() {
	if File_pkg_proto_follow_follow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_follow_follow_proto_rawDesc), len(file_pkg_proto_follow_follow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_follow_follow_proto_goTypes,
		DependencyIndexes: file_pkg_proto_follow_follow_proto_depIdxs,
		MessageInfos:      file_pkg_proto_follow_follow_proto_msgTypes,
	}.Build()
	File_pkg_proto_follow_follow_proto = out.File
	file_pkg_proto_follow_follow_proto_goTypes = nil
	file_pkg_proto_follow_follow_proto_depIdxs = nil
}
