// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: pkg/proto/follow/follow.proto

package follow

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FollowService_CreateFollow_FullMethodName             = "/follow.FollowService/CreateFollow"
	FollowService_GetFollow_FullMethodName                = "/follow.FollowService/GetFollow"
	FollowService_GetFollowersByFolloweeID_FullMethodName = "/follow.FollowService/GetFollowersByFolloweeID"
	FollowService_GetFolloweesByFollowerID_FullMethodName = "/follow.FollowService/GetFolloweesByFollowerID"
	FollowService_DeleteFollow_FullMethodName             = "/follow.FollowService/DeleteFollow"
)

// FollowServiceClient is the client API for FollowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service Definition
type FollowServiceClient interface {
	// Create
	CreateFollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error)
	// Read
	GetFollow(ctx context.Context, in *FollowRequestById, opts ...grpc.CallOption) (*FollowResponse, error)
	GetFollowersByFolloweeID(ctx context.Context, in *FollowRequestById, opts ...grpc.CallOption) (*IdListResponse, error)
	GetFolloweesByFollowerID(ctx context.Context, in *FollowRequestById, opts ...grpc.CallOption) (*IdListResponse, error)
	// Delete
	DeleteFollow(ctx context.Context, in *FollowRequestById, opts ...grpc.CallOption) (*DeleteFollowResponse, error)
}

type followServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFollowServiceClient(cc grpc.ClientConnInterface) FollowServiceClient {
	return &followServiceClient{cc}
}

func (c *followServiceClient) CreateFollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowResponse)
	err := c.cc.Invoke(ctx, FollowService_CreateFollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) GetFollow(ctx context.Context, in *FollowRequestById, opts ...grpc.CallOption) (*FollowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowResponse)
	err := c.cc.Invoke(ctx, FollowService_GetFollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) GetFollowersByFolloweeID(ctx context.Context, in *FollowRequestById, opts ...grpc.CallOption) (*IdListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdListResponse)
	err := c.cc.Invoke(ctx, FollowService_GetFollowersByFolloweeID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) GetFolloweesByFollowerID(ctx context.Context, in *FollowRequestById, opts ...grpc.CallOption) (*IdListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdListResponse)
	err := c.cc.Invoke(ctx, FollowService_GetFolloweesByFollowerID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) DeleteFollow(ctx context.Context, in *FollowRequestById, opts ...grpc.CallOption) (*DeleteFollowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFollowResponse)
	err := c.cc.Invoke(ctx, FollowService_DeleteFollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FollowServiceServer is the server API for FollowService service.
// All implementations must embed UnimplementedFollowServiceServer
// for forward compatibility.
//
// Service Definition
type FollowServiceServer interface {
	// Create
	CreateFollow(context.Context, *FollowRequest) (*FollowResponse, error)
	// Read
	GetFollow(context.Context, *FollowRequestById) (*FollowResponse, error)
	GetFollowersByFolloweeID(context.Context, *FollowRequestById) (*IdListResponse, error)
	GetFolloweesByFollowerID(context.Context, *FollowRequestById) (*IdListResponse, error)
	// Delete
	DeleteFollow(context.Context, *FollowRequestById) (*DeleteFollowResponse, error)
	mustEmbedUnimplementedFollowServiceServer()
}

// UnimplementedFollowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFollowServiceServer struct{}

func (UnimplementedFollowServiceServer) CreateFollow(context.Context, *FollowRequest) (*FollowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFollow not implemented")
}
func (UnimplementedFollowServiceServer) GetFollow(context.Context, *FollowRequestById) (*FollowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollow not implemented")
}
func (UnimplementedFollowServiceServer) GetFollowersByFolloweeID(context.Context, *FollowRequestById) (*IdListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowersByFolloweeID not implemented")
}
func (UnimplementedFollowServiceServer) GetFolloweesByFollowerID(context.Context, *FollowRequestById) (*IdListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFolloweesByFollowerID not implemented")
}
func (UnimplementedFollowServiceServer) DeleteFollow(context.Context, *FollowRequestById) (*DeleteFollowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFollow not implemented")
}
func (UnimplementedFollowServiceServer) mustEmbedUnimplementedFollowServiceServer() {}
func (UnimplementedFollowServiceServer) testEmbeddedByValue()                       {}

// UnsafeFollowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FollowServiceServer will
// result in compilation errors.
type UnsafeFollowServiceServer interface {
	mustEmbedUnimplementedFollowServiceServer()
}

func RegisterFollowServiceServer(s grpc.ServiceRegistrar, srv FollowServiceServer) {
	// If the following call panics, it indicates UnimplementedFollowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FollowService_ServiceDesc, srv)
}

func _FollowService_CreateFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).CreateFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_CreateFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).CreateFollow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_GetFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequestById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).GetFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_GetFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).GetFollow(ctx, req.(*FollowRequestById))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_GetFollowersByFolloweeID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequestById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).GetFollowersByFolloweeID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_GetFollowersByFolloweeID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).GetFollowersByFolloweeID(ctx, req.(*FollowRequestById))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_GetFolloweesByFollowerID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequestById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).GetFolloweesByFollowerID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_GetFolloweesByFollowerID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).GetFolloweesByFollowerID(ctx, req.(*FollowRequestById))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_DeleteFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequestById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).DeleteFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_DeleteFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).DeleteFollow(ctx, req.(*FollowRequestById))
	}
	return interceptor(ctx, in, info, handler)
}

// FollowService_ServiceDesc is the grpc.ServiceDesc for FollowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FollowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "follow.FollowService",
	HandlerType: (*FollowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFollow",
			Handler:    _FollowService_CreateFollow_Handler,
		},
		{
			MethodName: "GetFollow",
			Handler:    _FollowService_GetFollow_Handler,
		},
		{
			MethodName: "GetFollowersByFolloweeID",
			Handler:    _FollowService_GetFollowersByFolloweeID_Handler,
		},
		{
			MethodName: "GetFolloweesByFollowerID",
			Handler:    _FollowService_GetFolloweesByFollowerID_Handler,
		},
		{
			MethodName: "DeleteFollow",
			Handler:    _FollowService_DeleteFollow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/follow/follow.proto",
}
