services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      DB_DSN: "root:root@tcp(mysql:3306)/user_db?charset=utf8mb4&parseTime=True&loc=Local"
      GRPC_PORT: ":9090"
    networks:
      - go-service
  
  post-service:
    build: ./post-service
    ports:
      - "8082:8082"
    environment:
      DB_DSN: "root:root@tcp(mysql:3306)/user_db?charset=utf8mb4&parseTime=True&loc=Local"
      GRPC_PORT: ":9090"
    networks:
      - go-service

  comment-service:
    build: ./comment-service
    ports:
      - "8083:8083"
    environment:
      DB_DSN: "root:root@tcp(mysql:3306)/user_db?charset=utf8mb4&parseTime=True&loc=Local"
      GRPC_PORT: ":9090"
    networks:
      - go-service

  follow-service:
    build: ./follow-service
    ports:
      - "8084:8084"
    environment:
      DB_DSN: "root:root@tcp(mysql:3306)/user_db?charset=utf8mb4&parseTime=True&loc=Local"
      GRPC_PORT: ":9090"
    networks:
      - go-service

networks:
  go-service:
    driver: bridge