// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: pkg/proto/comment/comment.proto

package comment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommetnService_CreateComment_FullMethodName       = "/comment.CommetnService/CreateComment"
	CommetnService_GetCommentsByPostID_FullMethodName = "/comment.CommetnService/GetCommentsByPostID"
	CommetnService_GetComment_FullMethodName          = "/comment.CommetnService/GetComment"
	CommetnService_UpdateComment_FullMethodName       = "/comment.CommetnService/UpdateComment"
	CommetnService_DeleteComment_FullMethodName       = "/comment.CommetnService/DeleteComment"
)

// CommetnServiceClient is the client API for CommetnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service Definition
type CommetnServiceClient interface {
	// Create
	CreateComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error)
	// Read by PostID
	GetCommentsByPostID(ctx context.Context, in *CommentRequestByPostID, opts ...grpc.CallOption) (*CommentListResponse, error)
	// Read by ID
	GetComment(ctx context.Context, in *CommentRequestByID, opts ...grpc.CallOption) (*CommentResponse, error)
	// Update
	UpdateComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error)
	// Delete
	DeleteComment(ctx context.Context, in *CommentRequestByID, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
}

type commetnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommetnServiceClient(cc grpc.ClientConnInterface) CommetnServiceClient {
	return &commetnServiceClient{cc}
}

func (c *commetnServiceClient) CreateComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, CommetnService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commetnServiceClient) GetCommentsByPostID(ctx context.Context, in *CommentRequestByPostID, opts ...grpc.CallOption) (*CommentListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentListResponse)
	err := c.cc.Invoke(ctx, CommetnService_GetCommentsByPostID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commetnServiceClient) GetComment(ctx context.Context, in *CommentRequestByID, opts ...grpc.CallOption) (*CommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, CommetnService_GetComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commetnServiceClient) UpdateComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, CommetnService_UpdateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commetnServiceClient) DeleteComment(ctx context.Context, in *CommentRequestByID, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommentResponse)
	err := c.cc.Invoke(ctx, CommetnService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommetnServiceServer is the server API for CommetnService service.
// All implementations must embed UnimplementedCommetnServiceServer
// for forward compatibility.
//
// Service Definition
type CommetnServiceServer interface {
	// Create
	CreateComment(context.Context, *CommentRequest) (*CommentResponse, error)
	// Read by PostID
	GetCommentsByPostID(context.Context, *CommentRequestByPostID) (*CommentListResponse, error)
	// Read by ID
	GetComment(context.Context, *CommentRequestByID) (*CommentResponse, error)
	// Update
	UpdateComment(context.Context, *CommentRequest) (*CommentResponse, error)
	// Delete
	DeleteComment(context.Context, *CommentRequestByID) (*DeleteCommentResponse, error)
	mustEmbedUnimplementedCommetnServiceServer()
}

// UnimplementedCommetnServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommetnServiceServer struct{}

func (UnimplementedCommetnServiceServer) CreateComment(context.Context, *CommentRequest) (*CommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedCommetnServiceServer) GetCommentsByPostID(context.Context, *CommentRequestByPostID) (*CommentListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommentsByPostID not implemented")
}
func (UnimplementedCommetnServiceServer) GetComment(context.Context, *CommentRequestByID) (*CommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetComment not implemented")
}
func (UnimplementedCommetnServiceServer) UpdateComment(context.Context, *CommentRequest) (*CommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedCommetnServiceServer) DeleteComment(context.Context, *CommentRequestByID) (*DeleteCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedCommetnServiceServer) mustEmbedUnimplementedCommetnServiceServer() {}
func (UnimplementedCommetnServiceServer) testEmbeddedByValue()                        {}

// UnsafeCommetnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommetnServiceServer will
// result in compilation errors.
type UnsafeCommetnServiceServer interface {
	mustEmbedUnimplementedCommetnServiceServer()
}

func RegisterCommetnServiceServer(s grpc.ServiceRegistrar, srv CommetnServiceServer) {
	// If the following call panics, it indicates UnimplementedCommetnServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommetnService_ServiceDesc, srv)
}

func _CommetnService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommetnServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommetnService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommetnServiceServer).CreateComment(ctx, req.(*CommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommetnService_GetCommentsByPostID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequestByPostID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommetnServiceServer).GetCommentsByPostID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommetnService_GetCommentsByPostID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommetnServiceServer).GetCommentsByPostID(ctx, req.(*CommentRequestByPostID))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommetnService_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequestByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommetnServiceServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommetnService_GetComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommetnServiceServer).GetComment(ctx, req.(*CommentRequestByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommetnService_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommetnServiceServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommetnService_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommetnServiceServer).UpdateComment(ctx, req.(*CommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommetnService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequestByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommetnServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommetnService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommetnServiceServer).DeleteComment(ctx, req.(*CommentRequestByID))
	}
	return interceptor(ctx, in, info, handler)
}

// CommetnService_ServiceDesc is the grpc.ServiceDesc for CommetnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommetnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comment.CommetnService",
	HandlerType: (*CommetnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateComment",
			Handler:    _CommetnService_CreateComment_Handler,
		},
		{
			MethodName: "GetCommentsByPostID",
			Handler:    _CommetnService_GetCommentsByPostID_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _CommetnService_GetComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _CommetnService_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _CommetnService_DeleteComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/comment/comment.proto",
}
