// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: pkg/proto/comment/comment.proto

package comment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message Definition
type CommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        uint32                 `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentRequest) Reset() {
	*x = CommentRequest{}
	mi := &file_pkg_proto_comment_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentRequest) ProtoMessage() {}

func (x *CommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_comment_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentRequest.ProtoReflect.Descriptor instead.
func (*CommentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_comment_comment_proto_rawDescGZIP(), []int{0}
}

func (x *CommentRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        uint32                 `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentResponse) Reset() {
	*x = CommentResponse{}
	mi := &file_pkg_proto_comment_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentResponse) ProtoMessage() {}

func (x *CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_comment_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentResponse.ProtoReflect.Descriptor instead.
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_comment_comment_proto_rawDescGZIP(), []int{1}
}

func (x *CommentResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentResponse) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CommentResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CommentRequestByPostID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentRequestByPostID) Reset() {
	*x = CommentRequestByPostID{}
	mi := &file_pkg_proto_comment_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentRequestByPostID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentRequestByPostID) ProtoMessage() {}

func (x *CommentRequestByPostID) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_comment_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentRequestByPostID.ProtoReflect.Descriptor instead.
func (*CommentRequestByPostID) Descriptor() ([]byte, []int) {
	return file_pkg_proto_comment_comment_proto_rawDescGZIP(), []int{2}
}

func (x *CommentRequestByPostID) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type CommentListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentResponse     `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentListResponse) Reset() {
	*x = CommentListResponse{}
	mi := &file_pkg_proto_comment_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListResponse) ProtoMessage() {}

func (x *CommentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_comment_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListResponse.ProtoReflect.Descriptor instead.
func (*CommentListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_comment_comment_proto_rawDescGZIP(), []int{3}
}

func (x *CommentListResponse) GetComments() []*CommentResponse {
	if x != nil {
		return x.Comments
	}
	return nil
}

type CommentRequestByID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentRequestByID) Reset() {
	*x = CommentRequestByID{}
	mi := &file_pkg_proto_comment_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentRequestByID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentRequestByID) ProtoMessage() {}

func (x *CommentRequestByID) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_comment_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentRequestByID.ProtoReflect.Descriptor instead.
func (*CommentRequestByID) Descriptor() ([]byte, []int) {
	return file_pkg_proto_comment_comment_proto_rawDescGZIP(), []int{4}
}

func (x *CommentRequestByID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_pkg_proto_comment_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_comment_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_comment_comment_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_proto_comment_comment_proto protoreflect.FileDescriptor

const file_pkg_proto_comment_comment_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/comment/comment.proto\x12\acomment\"l\n" +
	"\x0eCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\rR\x06postId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"\x8b\x01\n" +
	"\x0fCommentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\rR\x06postId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\"1\n" +
	"\x16CommentRequestByPostID\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"K\n" +
	"\x13CommentListResponse\x124\n" +
	"\bcomments\x18\x01 \x03(\v2\x18.comment.CommentResponseR\bcomments\"$\n" +
	"\x12CommentRequestByID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x81\x03\n" +
	"\x0eCommetnService\x12B\n" +
	"\rCreateComment\x12\x17.comment.CommentRequest\x1a\x18.comment.CommentResponse\x12T\n" +
	"\x13GetCommentsByPostID\x12\x1f.comment.CommentRequestByPostID\x1a\x1c.comment.CommentListResponse\x12C\n" +
	"\n" +
	"GetComment\x12\x1b.comment.CommentRequestByID\x1a\x18.comment.CommentResponse\x12B\n" +
	"\rUpdateComment\x12\x17.comment.CommentRequest\x1a\x18.comment.CommentResponse\x12L\n" +
	"\rDeleteComment\x12\x1b.comment.CommentRequestByID\x1a\x1e.comment.DeleteCommentResponseB\x1cZ\x1aservices/pkg/proto/commentb\x06proto3"

var (
	file_pkg_proto_comment_comment_proto_rawDescOnce sync.Once
	file_pkg_proto_comment_comment_proto_rawDescData []byte
)

func file_pkg_proto_comment_comment_proto_rawDescGZIP() []byte {
	file_pkg_proto_comment_comment_proto_rawDescOnce.Do(func() {
		file_pkg_proto_comment_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_comment_comment_proto_rawDesc), len(file_pkg_proto_comment_comment_proto_rawDesc)))
	})
	return file_pkg_proto_comment_comment_proto_rawDescData
}

var file_pkg_proto_comment_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_proto_comment_comment_proto_goTypes = []any{
	(*CommentRequest)(nil),         // 0: comment.CommentRequest
	(*CommentResponse)(nil),        // 1: comment.CommentResponse
	(*CommentRequestByPostID)(nil), // 2: comment.CommentRequestByPostID
	(*CommentListResponse)(nil),    // 3: comment.CommentListResponse
	(*CommentRequestByID)(nil),     // 4: comment.CommentRequestByID
	(*DeleteCommentResponse)(nil),  // 5: comment.DeleteCommentResponse
}
var file_pkg_proto_comment_comment_proto_depIdxs = []int32{
	1, // 0: comment.CommentListResponse.comments:type_name -> comment.CommentResponse
	0, // 1: comment.CommetnService.CreateComment:input_type -> comment.CommentRequest
	2, // 2: comment.CommetnService.GetCommentsByPostID:input_type -> comment.CommentRequestByPostID
	4, // 3: comment.CommetnService.GetComment:input_type -> comment.CommentRequestByID
	0, // 4: comment.CommetnService.UpdateComment:input_type -> comment.CommentRequest
	4, // 5: comment.CommetnService.DeleteComment:input_type -> comment.CommentRequestByID
	1, // 6: comment.CommetnService.CreateComment:output_type -> comment.CommentResponse
	3, // 7: comment.CommetnService.GetCommentsByPostID:output_type -> comment.CommentListResponse
	1, // 8: comment.CommetnService.GetComment:output_type -> comment.CommentResponse
	1, // 9: comment.CommetnService.UpdateComment:output_type -> comment.CommentResponse
	5, // 10: comment.CommetnService.DeleteComment:output_type -> comment.DeleteCommentResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_comment_comment_proto_init() }
func file_pkg_proto_comment_comment_proto_init() {
	if File_pkg_proto_comment_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_comment_comment_proto_rawDesc), len(file_pkg_proto_comment_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_comment_comment_proto_goTypes,
		DependencyIndexes: file_pkg_proto_comment_comment_proto_depIdxs,
		MessageInfos:      file_pkg_proto_comment_comment_proto_msgTypes,
	}.Build()
	File_pkg_proto_comment_comment_proto = out.File
	file_pkg_proto_comment_comment_proto_goTypes = nil
	file_pkg_proto_comment_comment_proto_depIdxs = nil
}
