// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: pkg/proto/post/post.proto

package post

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message Definition
type PostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	mi := &file_pkg_proto_post_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_post_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_post_post_proto_rawDescGZIP(), []int{0}
}

type PostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	mi := &file_pkg_proto_post_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_post_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_post_post_proto_rawDescGZIP(), []int{1}
}

type PostListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostResponse        `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostListResponse) Reset() {
	*x = PostListResponse{}
	mi := &file_pkg_proto_post_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostListResponse) ProtoMessage() {}

func (x *PostListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_post_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostListResponse.ProtoReflect.Descriptor instead.
func (*PostListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_post_post_proto_rawDescGZIP(), []int{2}
}

func (x *PostListResponse) GetPosts() []*PostResponse {
	if x != nil {
		return x.Posts
	}
	return nil
}

var File_pkg_proto_post_post_proto protoreflect.FileDescriptor

const file_pkg_proto_post_post_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/post/post.proto\x12\x04post\"\r\n" +
	"\vPostRequest\"\x0e\n" +
	"\fPostResponse\"<\n" +
	"\x10PostListResponse\x12(\n" +
	"\x05posts\x18\x01 \x03(\v2\x12.post.PostResponseR\x05posts2\r\n" +
	"\vPostServiceB\x19Z\x17services/pkg/proto/postb\x06proto3"

var (
	file_pkg_proto_post_post_proto_rawDescOnce sync.Once
	file_pkg_proto_post_post_proto_rawDescData []byte
)

func file_pkg_proto_post_post_proto_rawDescGZIP() []byte {
	file_pkg_proto_post_post_proto_rawDescOnce.Do(func() {
		file_pkg_proto_post_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_post_post_proto_rawDesc), len(file_pkg_proto_post_post_proto_rawDesc)))
	})
	return file_pkg_proto_post_post_proto_rawDescData
}

var file_pkg_proto_post_post_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_post_post_proto_goTypes = []any{
	(*PostRequest)(nil),      // 0: post.PostRequest
	(*PostResponse)(nil),     // 1: post.PostResponse
	(*PostListResponse)(nil), // 2: post.PostListResponse
}
var file_pkg_proto_post_post_proto_depIdxs = []int32{
	1, // 0: post.PostListResponse.posts:type_name -> post.PostResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_post_post_proto_init() }
func file_pkg_proto_post_post_proto_init() {
	if File_pkg_proto_post_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_post_post_proto_rawDesc), len(file_pkg_proto_post_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_post_post_proto_goTypes,
		DependencyIndexes: file_pkg_proto_post_post_proto_depIdxs,
		MessageInfos:      file_pkg_proto_post_post_proto_msgTypes,
	}.Build()
	File_pkg_proto_post_post_proto = out.File
	file_pkg_proto_post_post_proto_goTypes = nil
	file_pkg_proto_post_post_proto_depIdxs = nil
}
