# just for the test, nothing more
server {
    listen 80;
    server_name example.com;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}

# this is real one

# Gateway
server {
    listen 80;
    server_name gateway.com;

    location /api/ {
	    proxy_pass http://gateway_backend;
    }
}

# Origin Server for Static Resource
server {
    listen 80;
    server_name origin.com;

    location /static/ {
        root /data/static;
    }
}