# just for the test, nothing more
server {
    listen 80;
    server_name example.local;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}

# this is real one

# Gateway
server {
    listen 80;
    server_name gateway.internal;

    location /api/ {
        # allow http://bff;
        # deny all;

	    proxy_pass http://gateway_backend;
    }
}

# Origin Server for Static Resource
server {
    listen 80;
    server_name origin.external;

    location /static/ {
        alias /usr/share/nginx/html/static/;
    }
}