# Upstream for the API Gateway
# Defines the pool of backend servers for the API gateway.
upstream gateway_backend {
    # For local development, 'localhost' is used.
    server localhost:8080;

    # In a containerized environment (e.g., Docker), you would use the service name.
    # The 'gateway' service name will be resolved by the Docker's internal DNS.
    # server gateway:8080;

}